# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0E1112)
$foreground = rgb(C7E5E0)
$color0 = rgb(37393A)
$color1 = rgb(017076)
$color2 = rgb(527134)
$color3 = rgb(397B41)
$color4 = rgb(607639)
$color5 = rgb(887745)
$color6 = rgb(47877C)
$color7 = rgb(A6D1CA)
$color8 = rgb(75928D)
$color9 = rgb(02969E)
$color10 = rgb(6D9746)
$color11 = rgb(4CA457)
$color12 = rgb(809D4B)
$color13 = rgb(B59F5C)
$color14 = rgb(5FB4A6)
$color15 = rgb(A6D1CA)
