[colors.primary]
background = '#21231a'
foreground = '#f3f3f2'

[colors.cursor]
text = '#21231a'
cursor = '#f3f3f2'

[colors.vi_mode_cursor]
text = '#21231a'
cursor = '#bbca81'

[colors.search.matches]
foreground = '#2d3021'
background = '#70c281'

[colors.search.focused_match]
foreground = '#2d3021'
background = '#bbca81'

[colors.footer_bar]
foreground = '#2d3021'
background = '#e6e7e4'

[colors.hints.start]
foreground = '#2d3021'
background = '#88c36f'

[colors.hints.end]
foreground = '#2d3021'
background = '#88c36f'

[colors.selection]
text = '#b5b6af'
background = '#2d3021'


[colors.normal]
black   = '#2d3021'
red     = '#fd4663'
green   = '#bbca81'
yellow  = '#88c36f'
blue    = '#70c281'
magenta = '#cfd9a5'
cyan    = '#b5daa5'
white   = '#f3f3f2'


[colors.bright]
black   = '#6a6d5e'
red     = '#fd4663'
green   = '#bbca81'
yellow  = '#88c36f'
blue    = '#70c281'
magenta = '#cfd9a5'
cyan    = '#b5daa5'
white   = '#f3f3f2'


[colors.dim]
black   = '#2d3021'
red     = '#fd4663'
green   = '#bbca81'
yellow  = '#88c36f'
blue    = '#70c281'
magenta = '#cfd9a5'
cyan    = '#b5daa5'
white   = '#f3f3f2'
