[colors.primary]
background = '#22231a'
foreground = '#f3f3f2'

[colors.cursor]
text = '#22231a'
cursor = '#f3f3f2'

[colors.vi_mode_cursor]
text = '#22231a'
cursor = '#bcc883'

[colors.search.matches]
foreground = '#2e3021'
background = '#71c17f'

[colors.search.focused_match]
foreground = '#2e3021'
background = '#bcc883'

[colors.footer_bar]
foreground = '#2e3021'
background = '#e6e7e4'

[colors.hints.start]
foreground = '#2e3021'
background = '#8bc171'

[colors.hints.end]
foreground = '#2e3021'
background = '#8bc171'

[colors.selection]
text = '#b5b6af'
background = '#2e3021'


[colors.normal]
black   = '#2e3021'
red     = '#fd4663'
green   = '#bcc883'
yellow  = '#8bc171'
blue    = '#71c17f'
magenta = '#cfd8a7'
cyan    = '#b6d8a6'
white   = '#f3f3f2'


[colors.bright]
black   = '#6a6e5e'
red     = '#fd4663'
green   = '#bcc883'
yellow  = '#8bc171'
blue    = '#71c17f'
magenta = '#cfd8a7'
cyan    = '#b6d8a6'
white   = '#f3f3f2'


[colors.dim]
black   = '#2e3021'
red     = '#fd4663'
green   = '#bcc883'
yellow  = '#8bc171'
blue    = '#71c17f'
magenta = '#cfd8a7'
cyan    = '#b6d8a6'
white   = '#f3f3f2'
