[colors.primary]
background = '#1a1d23'
foreground = '#f2f2f3'

[colors.cursor]
text = '#1a1d23'
cursor = '#f2f2f3'

[colors.vi_mode_cursor]
text = '#1a1d23'
cursor = '#7b95d1'

[colors.search.matches]
foreground = '#212630'
background = '#a970c2'

[colors.search.focused_match]
foreground = '#212630'
background = '#7b95d1'

[colors.footer_bar]
foreground = '#212630'
background = '#e4e5e7'

[colors.hints.start]
foreground = '#212630'
background = '#806bc7'

[colors.hints.end]
foreground = '#212630'
background = '#806bc7'

[colors.selection]
text = '#afb1b6'
background = '#212630'


[colors.normal]
black   = '#212630'
red     = '#fd4663'
green   = '#7b95d1'
yellow  = '#8a76d3'
blue    = '#a970c2'
magenta = '#a1b3de'
cyan    = '#b0a3dc'
white   = '#f2f2f3'


[colors.bright]
black   = '#626872'
red     = '#fd4663'
green   = '#7b95d1'
yellow  = '#8a76d3'
blue    = '#a970c2'
magenta = '#a1b3de'
cyan    = '#b0a3dc'
white   = '#f2f2f3'


[colors.dim]
black   = '#212630'
red     = '#fd4663'
green   = '#7b95d1'
yellow  = '#8a76d3'
blue    = '#a970c2'
magenta = '#a1b3de'
cyan    = '#b0a3dc'
white   = '#f2f2f3'
